[package]
name = "meif_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
log4rs = "1.4.0"
ureq = "3.1.2"
tokio = { version = "1.44.2", features = ["full"] }
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_xml = "0.9.1"
